apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonMetadata:
  labels:
    app: student-management
    managed-by: kustomize

resources:
- configmap.yaml
- pvc.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app: student-management

replicas:
- name: student-management-app
  count: 2
