apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: default
  labels:
    app: student-management
spec:
  type: LoadBalancer
  selector:
    app: student-management
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  sessionAffinity: None
